vim.cmd "colorscheme gruvbox"

require "boran.options"
require "boran.plugins"
require "boran.commands"
require "boran.lsp"
require "boran.telescope"
require "boran.treesitter"
require "boran.autopairs"
require "boran.comment"
require "boran.gitsigns"
require "boran.keymaps"
require "boran.neovide"
require "boran.nvim-tree"
require "boran.rainbow-delimiters"
require "boran.toggleterm"

